import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";

const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-mega",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={lexendDeca.className}
      >
        {/* Outer container - full screen */}
        <div className="min-h-screen flex items-center justify-center p-4">
          {/* Main container - card style like reference */}
          <div className="h-[800px] w-[1000px] max-w-[1000px] border-4 border-border shadow-[10px_10px_0_0_#000] rounded-[5px] bg-background overflow-hidden">
            {/* Content wrapper */}
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
